[package]
name = "raytracer"
version = "0.1.0"
authors = ["Nyrox <root@nyrox.tech>"]

[dependencies]
cgmath={version="*", features=["serde"]}
image="*"
num-traits="*"
rand="*"
crossbeam-utils="0.5.0"
crossbeam="*"
num_cpus="*"
serde="*"
serde_json="*"
serde_derive="*"


[workspace]
members=[
	"cli",
	"server",
]