
[tasks.build]
clear=true
dependencies=["cargo_build", "bindgen"]


[tasks.cargo_build]
command="cargo"
args=["build", "--target=wasm32-unknown-unknown"]

[tasks.bindgen]
command="wasm-bindgen"
args=["target/wasm32-unknown-unknown/debug/editor_frontend.wasm", "--out-dir", "pkg"]
