[package]
name = "cli"
version = "0.1.0"
authors = ["Nyrox <mark.oliver@hotmail.de>"]
edition="2018" 

[dependencies]
raytracer={ path="../" }
image="*"
simplelog="*"
core={ path="../core" }
cgmath="0.17"