[package]
name = "cli"
version = "0.1.0"
authors = ["Nyrox <mark.oliver@hotmail.de>"]
edition="2018" 

[dependencies]
raytracer={ path="../" }
core={ path="../core" }
image="*"
simplelog="*"
cgmath="*"
structopt="0.2"
ron="0.5"
serde="1"
serde_json="1"
rmp-serde="*"
serde_bytes="*"
log="*"