[package]
name = "server"
version = "0.1.0"
authors = ["Nyrox <mark.oliver@hotmail.de>"]
edition="2018"

[dependencies]
raytracer={ path="../" }
image="*"
cgmath="*"
ws="*"
serde="*"
serde_json="*"
simplelog="*"
log="*"